[package]
name = "nns_proxy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9"
ic-cdk = "0.11"
ic-stable-structures = "0.6"
serde = "1.0"
serde_bytes = "0.11"
