[dependencies]
core = "2.0.0"

[toolchain]
moc = "1.2.0"

[canisters]
test_canister = "packages/pic/tests/test-canister/main.mo"
clock = "examples/clock/src/main.mo"
counter = "examples/counter/src/main.mo"
google_search = "examples/google_search/src/main.mo"
multicanister = "examples/multicanister/src/main.mo"
phonebook = "examples/multicanister/phonebook/phonebook.mo"
superheroes = "examples/multicanister/superheroes/superheroes.mo"
reentrancy = "examples/reentrancy/src/main.mo"
