packages:
  - 'examples/clock/tests'
  - 'examples/counter/tests'
  - 'examples/google_search/tests'
  - 'examples/icp_features/tests'
  - 'examples/multicanister/tests'
  - 'examples/nns_proxy/tests'
  - 'examples/todo/tests'
  - 'packages/pic'
  - 'packages/pic-server'
  - 'docs'
