[package]
name = "icp_features"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.18"
icrc-ledger-types = "0.1"

serde = "1.0"
serde_bytes = "0.11"
