/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const PublicKeyResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Time = IDL.Int;
  
  return IDL.Service({
    'ecdsa_public_key_size' : IDL.Func([IDL.Text], [PublicKeyResult], []),
    'get_certificate' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
    'get_time' : IDL.Func([], [Time], ['query']),
    'get_value' : IDL.Func([], [IDL.Nat], ['query']),
    'increment_value_after_call' : IDL.Func([], [IDL.Nat], []),
    'noop' : IDL.Func([], [], []),
    'print_log' : IDL.Func([IDL.Text], [], []),
    'schnorr_public_key_size' : IDL.Func([IDL.Text], [PublicKeyResult], []),
    'set_certified_data' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'set_value' : IDL.Func([IDL.Nat], [], []),
    'vetkd_public_key_size' : IDL.Func([IDL.Text], [PublicKeyResult], []),
    'whoami' : IDL.Func([], [IDL.Principal], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };