/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const PublicKeyResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Time = IDL.Int;
  
  return IDL.Service({
    'ecdsa_public_key_size' : IDL.Func([IDL.Text], [PublicKeyResult], []),
    'get_time' : IDL.Func([], [Time], ['query']),
    'print_log' : IDL.Func([IDL.Text], [], []),
    'schnorr_public_key_size' : IDL.Func([IDL.Text], [PublicKeyResult], []),
    'vetkd_public_key_size' : IDL.Func([IDL.Text], [PublicKeyResult], []),
  });
};

export const init = ({ IDL }) => { return []; };