name: check_commit_messages

on:
  merge_group:
    types: [checks_requested]

jobs:
  check_commit_messages:
    name: check_commit_messages:required
    uses: dfinity/ci-tools/.github/workflows/check-commit-messages.yaml@main
