name: test

on:
  merge_group:
  pull_request:

jobs:
  unit_test:
    name: unit_test:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@afeee4fbdc0683a88ec5a74ed7f59a2ce0e833ad # main

      - name: Setup
        run: pnpm run setup

      - name: Test
        run: pnpm test:pic

  e2e_test_nodejs:
    name: e2e_test_nodejs:required
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@afeee4fbdc0683a88ec5a74ed7f59a2ce0e833ad # main

      - name: Setup
        run: pnpm run setup

      - name: Setup Canister Toolchain
        uses: ./.github/actions/setup-canister-toolchain
        with:
          package-manager: pnpm

      - name: Build
        run: pnpm run build

      - name: Build Examples
        run: pnpm build:examples

      - name: Test Examples
        run: pnpm test:examples

  e2e_test_bun:
    name: e2e_test_bun:required
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: '.bun-version'

      - name: Install Dependencies
        shell: bash
        run: bun i --frozen-lockfile

      - name: Setup
        run: bun run setup

      - name: Setup Canister Toolchain
        uses: ./.github/actions/setup-canister-toolchain
        with:
          package-manager: bun

      - name: Build
        run: bun run build

      - name: Build Examples
        run: bun build:examples

      - name: Test Examples
        run: bun test:examples
