name: lint

on:
  merge_group:
  pull_request:

jobs:
  lint:
    name: lint:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@afeee4fbdc0683a88ec5a74ed7f59a2ce0e833ad # main

      - name: Check TypeScript Formatting
        run: pnpm format:check

      - name: Check Rust Linting
        run: cargo clippy

      - name: Check Rust formatting
        run: cargo fmt -- --check
