name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: lint:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Check TypeScript Formatting
        run: bun format:check

      - name: Check Rust Linting
        run: cargo clippy

      - name: Check Rust formatting
        run: cargo fmt -- --check
