name: Test (Bun)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_bun:
    name: Test (Bun)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-bun

      - uses: ./.github/actions/setup-dfx

      - name: Build
        run: bun run build

      - name: Build Examples
        run: bun build:examples

      - name: Test Examples
        run: bun test:examples
