name: test_nodejs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_nodejs:
    name: test_nodejs:required
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: 'auto'

      - name: Build
        run: pnpm run build

      - name: Build Examples
        run: pnpm build:examples

      - name: Test Examples
        run: pnpm test:examples
