name: Test (NodeJS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_nodejs:
    name: Test (NodeJS)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pnpm

      - uses: ./.github/actions/setup-dfx

      - name: Build
        run: pnpm run build

      - name: Build Examples
        run: pnpm build:examples

      - name: Test Examples
        run: pnpm test:examples
