name: test_bun

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_bun:
    name: test_bun:required
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: 'auto'

      - name: Build
        run: bun run build

      - name: Build Examples
        run: bun build:examples

      - name: Test Examples
        run: bun test:examples
